### ISSUE TITLE
Failed to handle builtin modules on Darwin

### ISSUE THREAD

**Issue by jiaxuan** [CoatiSoftware/SourcetrailPythonIndexer#23]
The indexer fails to handle some builtin modules on Darwin. For instance:
```
$ cat a.py
import sys

$ python3.6 --version
Python 3.6.7

$ uname -a
Darwin ... 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64

$ python3.6 run.py --database-file-path=a.srctrldb --source-file-path=a.py
Loaded database is compatible.
Traceback (most recent call last):
  File ".../SourcetrailPythonIndexer/run.py", line 52, in <module>
    main()
  File ".../SourcetrailPythonIndexer/run.py", line 38, in main
    indexSourceFile(sourceFilePath, args.verbose)
  File ".../SourcetrailPythonIndexer/run.py", line 48, in indexSourceFile
    indexer.indexSourceFile(sourceFilePath, workingDirectory, astVisitorClient, verbose)
  File ".../SourcetrailPythonIndexer/indexer.py", line 96, in indexSourceFile
    astVisitor.traverseNode(module_node)
  File ".../SourcetrailPythonIndexer/indexer.py", line 161, in traverseNode
    self.traverseNode(c)
  File ".../SourcetrailPythonIndexer/indexer.py", line 161, in traverseNode
    self.traverseNode(c)
  File ".../SourcetrailPythonIndexer/indexer.py", line 161, in traverseNode
    self.traverseNode(c)
  File ".../SourcetrailPythonIndexer/indexer.py", line 153, in traverseNode
    self.beginVisitName(node)
  File ".../SourcetrailPythonIndexer/indexer.py", line 244, in beginVisitName
    referencedNameHierarchy = self.getNameHierarchyFromModulePathOfDefinition(definition)
  File ".../SourcetrailPythonIndexer/indexer.py", line 515, in getNameHierarchyFromModulePathOfDefinition
    nameHierarchy = self.getNameHierarchyFromModuleFilePath(definition.module_path)
  File ".../SourcetrailPythonIndexer/indexer.py", line 482, in getNameHierarchyFromModuleFilePath
    filePath = os.path.abspath(filePath)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/posixpath.py", line 371, in abspath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
The same error occured to the `posix` module as well, but it worked for the `signal` builtin module.

Tested against commit 74fb934fd373fe2e6764507875f0792fae35b88e

**Comment by jiaxuan** [comment]
Forgot to mention, it's tested against commit `74fb934fd373fe2e6764507875f0792fae35b88e`

**Comment by mlangkabel** [comment]
Hi @jiaxuan, thanks for providing this detailed issue report. We managed to reproduce the crash on macOS and are working on a fix.

**Comment by mlangkabel** [comment]
We recently applied some fixes to the code that is responsible for solving names of modules based on file paths (e.g. the exact code that caused this issue). We re-tested the current HEAD of the master branch (commit c861222d) on macOS again and the issue is gone. 

@jiaxuan: Can you please verify that this issue is fixed for you as well?

**Comment by jiaxuan** [comment]
The original issue with `import sys` is gone now. But it still failed for this simple test case:

```
$ cat a.py
import os

os.environ.setdefault('TEST', 'abc')

$ python3.6 run.py --database-file-path=a.srctrldb --source-file-path=a.py
Loaded database is compatible.
Traceback (most recent call last):
  File "run.py", line 52, in <module>
    main()
  File "run.py", line 38, in main
    indexSourceFile(sourceFilePath, args.verbose)
  File "run.py", line 48, in indexSourceFile
    indexer.indexSourceFile(sourceFilePath, workingDirectory, astVisitorClient, verbose)
  File ".../SourcetrailPythonIndexer/indexer.py", line 96, in indexSourceFile
    astVisitor.traverseNode(module_node)
  File ".../SourcetrailPythonIndexer/indexer.py", line 169, in traverseNode
    self.traverseNode(c)
  File ".../SourcetrailPythonIndexer/indexer.py", line 169, in traverseNode
    self.traverseNode(c)
  File ".../SourcetrailPythonIndexer/indexer.py", line 169, in traverseNode
    self.traverseNode(c)
  File ".../SourcetrailPythonIndexer/indexer.py", line 161, in traverseNode
    self.beginVisitName(node)
  File ".../SourcetrailPythonIndexer/indexer.py", line 241, in beginVisitName
    if self.recordModuleReference(node, definition):
  File ".../SourcetrailPythonIndexer/indexer.py", line 349, in recordModuleReference
    self.client.recordQualifierLocation(referencedSymbolId, getSourceRangeOfNode(node))
  File ".../SourcetrailPythonIndexer/indexer.py", line 817, in recordQualifierLocation
    return srctrl.recordQualifierLocation(
AttributeError: module 'sourcetraildb' has no attribute 'recordQualifierLocation'

```

**Comment by mlangkabel** [comment]
Thank you very much for verifying that the issue is fixed. 

It looks like you are using a new version of the SourcetrailPythonIndexer with an older version of SourcetrailDB. Since then the SourcetrailDB interface has introduced a new method which your SourcetrailPythonIndexer is now trying to call. To make this work, just update your SourcetrailDB. 

However, it i not ideal that it just crashes and doesn't show this info to the user. But it looks like issue #8 is there to fix that ;)
